#!/bin/bash

# set compiler
export FC=mpif90
export CC=mpicc
export CXX=mpic++

# directory to build in
export HGODAS_BUILD_DIR=$HGODAS_ROOT_DIR/build/gcc

#--------------------------------------------------------------------------------
# The following are needed for the runtime

export MPIEXEC=mpirun
ulimit -s unlimied
export OMP_NUM_THREADS=1

# other required default directory locations
export HGODAS_BIN_DIR=$HGODAS_BUILD_DIR/bin
export HGODAS_DATA_DIR=$HGODAS_ROOT_DIR/DATA
export HGODAS_SCRATCH_DIR=$EXP_DIR/WRK
