#!/bin/bash
set -e
cat << \#\#

#================================================================================
#================================================================================
# Prep SOCA-3DVAR

# HARDCODED !!!
cd /scratch4/NCEPDEV/ocean/scrub/Guillaume.Vernieres/JEDI/soca/workflowrun/test001

# Copy static

